name: 'ct'
description: 'cloudticon'
inputs:
  ctToken:
    description: 'ct token'
    required: true
  version:
    description: 'ct token'
    required: true
    default: "0.2.1"
  ghToken:
    description: 'github token'
    required: true
runs:
  using: "composite"
  steps:
    - run: npm install @cloudticon/cli@${{ inputs.version }} -g
      shell: bash
    - run: cat package.json| jq 'del(.devDependencies) | .dependencies |= {"@cloudticon/cdk":."@cloudticon/cdk"}' > package.json
      shell: bash
    - run: yarn install
      shell: bash
    - run: ct deploy
      shell: bash
      env:
        CT_TOKEN: ${{ inputs.ctToken }}
        GITHUB_TOKEN: ${{ inputs.ghToken }}